#!/bin/bash

#PBS -l select=1:host=k100:ncpus=8:ngpus=1:mem=100gb
#PBS -l walltime=24:00:00
#PBS -q mwacgpu
#PBS -M k.rowell@unsw.edu.au 
#PBS -m ae
#PBS -j oe

module load cuda/12.5.0 

cd $PBS_O_WORKDIR

apptainer run --nv /srv/scratch/sbf/apptainers/boltz.sif boltz predict /srv/scratch/z3374843/Loki-ASV2_in_silico/folded_proteins/Boltz+MMSeqs2-GPU/boltz_format_fastas  --cache /srv/scratch/sbf/cache/
